# permissions for end users to edit bookstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: bookstore-editor-role
rules:
- apiGroups:
  - reader.com
  resources:
  - bookstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reader.com
  resources:
  - bookstores/status
  verbs:
  - get
