apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: default
spec:
  ports:
  - nodePort: 30002
    port: 3100
    protocol: TCP
    targetPort: 9090
  selector:
    app: bookstore-app
